# Generated by Django 3.0.3 on 2020-03-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.Consumer'),
        ),
    ]
